import {isRunningInExpoGo, requireOptionalNativeModule} from 'expo';
import {StatusBar} from 'expo-status-bar';
import {useEffect, useState} from 'react';
import {Pressable, StyleSheet, Text, View} from 'react-native';

/**
 * Uses the local Expo module in modules/device-metadata, generated by
 * `npx create-expo-module@57.0.1 device-metadata --local`.
 *
 * A local module is custom native code, and Expo Go ships a fixed set of native
 * modules, so it cannot load yours: `requireNativeModule('DeviceMetadata')`
 * throws there.
 *
 * Two checks, deliberately:
 *  - `requireOptionalNativeModule` asks the question that actually matters — is
 *    this native module linked into the binary? — and returns null instead of
 *    throwing when it is not.
 *  - `isRunningInExpoGo()` is only used to word the message. Do NOT use
 *    `Constants.executionEnvironment === 'storeClient'` for this: expo-constants
 *    documents StoreClient as "Expo Go or a development build", so that check is
 *    also true inside the development build that CAN load the module.
 */
const moduleIsLinked = requireOptionalNativeModule('DeviceMetadata') !== null;

type DeviceMetadataExports = typeof import('./modules/device-metadata');

const nativeModule: DeviceMetadataExports | null = moduleIsLinked
  ? (require('./modules/device-metadata') as DeviceMetadataExports)
  : null;

export default function App() {
  const [lastEvent, setLastEvent] = useState<string | null>(null);

  useEffect(() => {
    if (!nativeModule) return;
    const subscription = nativeModule.default.addListener('onChange', ({value}) => {
      setLastEvent(value);
    });
    return () => subscription.remove();
  }, []);

  if (!nativeModule) {
    return (
      <View style={styles.container}>
        <Text style={styles.title}>Development build required</Text>
        <Text style={styles.body}>
          {isRunningInExpoGo()
            ? 'You are in Expo Go, which cannot load custom native code.'
            : 'The DeviceMetadata native module is not linked into this binary.'}{' '}
          Build the app with `npx expo run:android` or `npx expo run:ios`.
        </Text>
        <StatusBar style="auto" />
      </View>
    );
  }

  const {default: DeviceMetadata, DeviceMetadataView} = nativeModule;

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Expo Modules API</Text>
      <Text style={styles.body}>Constant PI from native: {DeviceMetadata.PI}</Text>
      <Text style={styles.body}>Synchronous function: {DeviceMetadata.hello()}</Text>
      <Pressable
        accessibilityRole="button"
        style={styles.button}
        onPress={() => DeviceMetadata.setValueAsync(`sent at ${new Date().toLocaleTimeString()}`)}>
        <Text style={styles.buttonText}>Call setValueAsync</Text>
      </Pressable>
      <Text style={styles.body}>Last onChange event: {lastEvent ?? '(none yet)'}</Text>
      <DeviceMetadataView style={styles.nativeView} />
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, gap: 12},
  title: {fontSize: 20, fontWeight: '700'},
  body: {fontSize: 15, textAlign: 'center', lineHeight: 22},
  button: {backgroundColor: '#0a58ca', borderRadius: 8, paddingVertical: 10, paddingHorizontal: 18},
  buttonText: {color: '#fff', fontWeight: '600'},
  nativeView: {width: 200, height: 60, marginTop: 12},
});
